/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity{}

// FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity Asserts whether the live video is trustworthy - e.g. not from a fake webcam.
type FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity struct {
	Result     *string       `json:"result,omitempty"`
	Properties *VideoReasons `json:"properties,omitempty"`
}

// NewFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity instantiates a new FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity() *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity {
	this := FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity{}
	return &this
}

// NewFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrityWithDefaults instantiates a new FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrityWithDefaults() *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity {
	this := FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) SetResult(v string) {
	o.Result = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) GetProperties() VideoReasons {
	if o == nil || IsNil(o.Properties) {
		var ret VideoReasons
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) GetPropertiesOk() (*VideoReasons, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given VideoReasons and assigns it to the Properties field.
func (o *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) SetProperties(v VideoReasons) {
	o.Properties = &v
}

func (o FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

type NullableFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity struct {
	value *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity
	isSet bool
}

func (v NullableFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) Get() *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity {
	return v.value
}

func (v *NullableFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) Set(val *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) {
	v.value = val
	v.isSet = true
}

func (v NullableFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) IsSet() bool {
	return v.isSet
}

func (v *NullableFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity(val *FacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) *NullableFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity {
	return &NullableFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity{value: val, isSet: true}
}

func (v NullableFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFacialSimilarityVideoBreakdownImageIntegrityBreakdownSourceIntegrity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
