/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the FacialSimilarityPhotoBreakdownImageIntegrity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FacialSimilarityPhotoBreakdownImageIntegrity{}

// FacialSimilarityPhotoBreakdownImageIntegrity Asserts whether the quality and integrity of the uploaded files were sufficient to perform a face comparison.
type FacialSimilarityPhotoBreakdownImageIntegrity struct {
	Result    *string                                                `json:"result,omitempty"`
	Breakdown *FacialSimilarityPhotoBreakdownImageIntegrityBreakdown `json:"breakdown,omitempty"`
}

// NewFacialSimilarityPhotoBreakdownImageIntegrity instantiates a new FacialSimilarityPhotoBreakdownImageIntegrity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFacialSimilarityPhotoBreakdownImageIntegrity() *FacialSimilarityPhotoBreakdownImageIntegrity {
	this := FacialSimilarityPhotoBreakdownImageIntegrity{}
	return &this
}

// NewFacialSimilarityPhotoBreakdownImageIntegrityWithDefaults instantiates a new FacialSimilarityPhotoBreakdownImageIntegrity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFacialSimilarityPhotoBreakdownImageIntegrityWithDefaults() *FacialSimilarityPhotoBreakdownImageIntegrity {
	this := FacialSimilarityPhotoBreakdownImageIntegrity{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *FacialSimilarityPhotoBreakdownImageIntegrity) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityPhotoBreakdownImageIntegrity) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *FacialSimilarityPhotoBreakdownImageIntegrity) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *FacialSimilarityPhotoBreakdownImageIntegrity) SetResult(v string) {
	o.Result = &v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *FacialSimilarityPhotoBreakdownImageIntegrity) GetBreakdown() FacialSimilarityPhotoBreakdownImageIntegrityBreakdown {
	if o == nil || IsNil(o.Breakdown) {
		var ret FacialSimilarityPhotoBreakdownImageIntegrityBreakdown
		return ret
	}
	return *o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityPhotoBreakdownImageIntegrity) GetBreakdownOk() (*FacialSimilarityPhotoBreakdownImageIntegrityBreakdown, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *FacialSimilarityPhotoBreakdownImageIntegrity) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given FacialSimilarityPhotoBreakdownImageIntegrityBreakdown and assigns it to the Breakdown field.
func (o *FacialSimilarityPhotoBreakdownImageIntegrity) SetBreakdown(v FacialSimilarityPhotoBreakdownImageIntegrityBreakdown) {
	o.Breakdown = &v
}

func (o FacialSimilarityPhotoBreakdownImageIntegrity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FacialSimilarityPhotoBreakdownImageIntegrity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Breakdown) {
		toSerialize["breakdown"] = o.Breakdown
	}
	return toSerialize, nil
}

type NullableFacialSimilarityPhotoBreakdownImageIntegrity struct {
	value *FacialSimilarityPhotoBreakdownImageIntegrity
	isSet bool
}

func (v NullableFacialSimilarityPhotoBreakdownImageIntegrity) Get() *FacialSimilarityPhotoBreakdownImageIntegrity {
	return v.value
}

func (v *NullableFacialSimilarityPhotoBreakdownImageIntegrity) Set(val *FacialSimilarityPhotoBreakdownImageIntegrity) {
	v.value = val
	v.isSet = true
}

func (v NullableFacialSimilarityPhotoBreakdownImageIntegrity) IsSet() bool {
	return v.isSet
}

func (v *NullableFacialSimilarityPhotoBreakdownImageIntegrity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFacialSimilarityPhotoBreakdownImageIntegrity(val *FacialSimilarityPhotoBreakdownImageIntegrity) *NullableFacialSimilarityPhotoBreakdownImageIntegrity {
	return &NullableFacialSimilarityPhotoBreakdownImageIntegrity{value: val, isSet: true}
}

func (v NullableFacialSimilarityPhotoBreakdownImageIntegrity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFacialSimilarityPhotoBreakdownImageIntegrity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
