/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the WatchlistStandardReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WatchlistStandardReport{}

// WatchlistStandardReport struct for WatchlistStandardReport
type WatchlistStandardReport struct {
	ReadOnly interface{} `json:"readOnly,omitempty"`
	// The unique identifier for the report. Read-only.
	Id *string `json:"id,omitempty"`
	// The date and time at which the report was first initiated. Read-only.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// The API endpoint to retrieve the report. Read-only.
	Href *string `json:"href,omitempty"`
	// The current state of the report in the checking process. Read-only.
	Status *string `json:"status,omitempty"`
	// The result of the report. Read-only.
	Result *string `json:"result,omitempty"`
	// The sub_result of the report. It gives a more detailed result for document reports only, and will be null otherwise. Read-only.
	SubResult *string `json:"sub_result,omitempty"`
	// The ID of the check to which the report belongs. Read-only.
	CheckId *string `json:"check_id,omitempty"`
	// Array of objects with document ids that were used in the Onfido engine. [ONLY POPULATED FOR DOCUMENT AND FACIAL SIMILARITY REPORTS]
	Documents []ReportDocument `json:"documents,omitempty"`
	// Array of objects with id photo ids that were used in the Onfido engine.
	IdPhotos []FacialSimilarityReportMedia `json:"id_photos,omitempty"`
	// Array of objects with live photo ids that were used in the Onfido engine.
	LivePhotos []FacialSimilarityReportMedia `json:"live_photos,omitempty"`
	// Array of objects with live video ids that were used in the Onfido engine.
	LiveVideos []FacialSimilarityReportMedia `json:"live_videos,omitempty"`
	// Array of objects with motion capture ids that were used in the Onfido engine.
	MotionCaptures []FacialSimilarityReportMedia `json:"motion_captures,omitempty"`
	// The name of the report type.
	Name       string                       `json:"name"`
	Breakdown  *WatchlistStandardBreakdown  `json:"breakdown,omitempty"`
	Properties *WatchlistStandardProperties `json:"properties,omitempty"`
}

type _WatchlistStandardReport WatchlistStandardReport

// NewWatchlistStandardReport instantiates a new WatchlistStandardReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWatchlistStandardReport(name string) *WatchlistStandardReport {
	this := WatchlistStandardReport{}
	this.Name = name
	return &this
}

// NewWatchlistStandardReportWithDefaults instantiates a new WatchlistStandardReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWatchlistStandardReportWithDefaults() *WatchlistStandardReport {
	this := WatchlistStandardReport{}
	return &this
}

// GetReadOnly returns the ReadOnly field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WatchlistStandardReport) GetReadOnly() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ReadOnly
}

// GetReadOnlyOk returns a tuple with the ReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WatchlistStandardReport) GetReadOnlyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ReadOnly) {
		return nil, false
	}
	return &o.ReadOnly, true
}

// HasReadOnly returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasReadOnly() bool {
	if o != nil && !IsNil(o.ReadOnly) {
		return true
	}

	return false
}

// SetReadOnly gets a reference to the given interface{} and assigns it to the ReadOnly field.
func (o *WatchlistStandardReport) SetReadOnly(v interface{}) {
	o.ReadOnly = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WatchlistStandardReport) SetId(v string) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WatchlistStandardReport) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *WatchlistStandardReport) SetHref(v string) {
	o.Href = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *WatchlistStandardReport) SetStatus(v string) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *WatchlistStandardReport) SetResult(v string) {
	o.Result = &v
}

// GetSubResult returns the SubResult field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetSubResult() string {
	if o == nil || IsNil(o.SubResult) {
		var ret string
		return ret
	}
	return *o.SubResult
}

// GetSubResultOk returns a tuple with the SubResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetSubResultOk() (*string, bool) {
	if o == nil || IsNil(o.SubResult) {
		return nil, false
	}
	return o.SubResult, true
}

// HasSubResult returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasSubResult() bool {
	if o != nil && !IsNil(o.SubResult) {
		return true
	}

	return false
}

// SetSubResult gets a reference to the given string and assigns it to the SubResult field.
func (o *WatchlistStandardReport) SetSubResult(v string) {
	o.SubResult = &v
}

// GetCheckId returns the CheckId field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetCheckId() string {
	if o == nil || IsNil(o.CheckId) {
		var ret string
		return ret
	}
	return *o.CheckId
}

// GetCheckIdOk returns a tuple with the CheckId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetCheckIdOk() (*string, bool) {
	if o == nil || IsNil(o.CheckId) {
		return nil, false
	}
	return o.CheckId, true
}

// HasCheckId returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasCheckId() bool {
	if o != nil && !IsNil(o.CheckId) {
		return true
	}

	return false
}

// SetCheckId gets a reference to the given string and assigns it to the CheckId field.
func (o *WatchlistStandardReport) SetCheckId(v string) {
	o.CheckId = &v
}

// GetDocuments returns the Documents field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetDocuments() []ReportDocument {
	if o == nil || IsNil(o.Documents) {
		var ret []ReportDocument
		return ret
	}
	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetDocumentsOk() ([]ReportDocument, bool) {
	if o == nil || IsNil(o.Documents) {
		return nil, false
	}
	return o.Documents, true
}

// HasDocuments returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasDocuments() bool {
	if o != nil && !IsNil(o.Documents) {
		return true
	}

	return false
}

// SetDocuments gets a reference to the given []ReportDocument and assigns it to the Documents field.
func (o *WatchlistStandardReport) SetDocuments(v []ReportDocument) {
	o.Documents = v
}

// GetIdPhotos returns the IdPhotos field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetIdPhotos() []FacialSimilarityReportMedia {
	if o == nil || IsNil(o.IdPhotos) {
		var ret []FacialSimilarityReportMedia
		return ret
	}
	return o.IdPhotos
}

// GetIdPhotosOk returns a tuple with the IdPhotos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetIdPhotosOk() ([]FacialSimilarityReportMedia, bool) {
	if o == nil || IsNil(o.IdPhotos) {
		return nil, false
	}
	return o.IdPhotos, true
}

// HasIdPhotos returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasIdPhotos() bool {
	if o != nil && !IsNil(o.IdPhotos) {
		return true
	}

	return false
}

// SetIdPhotos gets a reference to the given []FacialSimilarityReportMedia and assigns it to the IdPhotos field.
func (o *WatchlistStandardReport) SetIdPhotos(v []FacialSimilarityReportMedia) {
	o.IdPhotos = v
}

// GetLivePhotos returns the LivePhotos field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetLivePhotos() []FacialSimilarityReportMedia {
	if o == nil || IsNil(o.LivePhotos) {
		var ret []FacialSimilarityReportMedia
		return ret
	}
	return o.LivePhotos
}

// GetLivePhotosOk returns a tuple with the LivePhotos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetLivePhotosOk() ([]FacialSimilarityReportMedia, bool) {
	if o == nil || IsNil(o.LivePhotos) {
		return nil, false
	}
	return o.LivePhotos, true
}

// HasLivePhotos returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasLivePhotos() bool {
	if o != nil && !IsNil(o.LivePhotos) {
		return true
	}

	return false
}

// SetLivePhotos gets a reference to the given []FacialSimilarityReportMedia and assigns it to the LivePhotos field.
func (o *WatchlistStandardReport) SetLivePhotos(v []FacialSimilarityReportMedia) {
	o.LivePhotos = v
}

// GetLiveVideos returns the LiveVideos field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetLiveVideos() []FacialSimilarityReportMedia {
	if o == nil || IsNil(o.LiveVideos) {
		var ret []FacialSimilarityReportMedia
		return ret
	}
	return o.LiveVideos
}

// GetLiveVideosOk returns a tuple with the LiveVideos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetLiveVideosOk() ([]FacialSimilarityReportMedia, bool) {
	if o == nil || IsNil(o.LiveVideos) {
		return nil, false
	}
	return o.LiveVideos, true
}

// HasLiveVideos returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasLiveVideos() bool {
	if o != nil && !IsNil(o.LiveVideos) {
		return true
	}

	return false
}

// SetLiveVideos gets a reference to the given []FacialSimilarityReportMedia and assigns it to the LiveVideos field.
func (o *WatchlistStandardReport) SetLiveVideos(v []FacialSimilarityReportMedia) {
	o.LiveVideos = v
}

// GetMotionCaptures returns the MotionCaptures field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetMotionCaptures() []FacialSimilarityReportMedia {
	if o == nil || IsNil(o.MotionCaptures) {
		var ret []FacialSimilarityReportMedia
		return ret
	}
	return o.MotionCaptures
}

// GetMotionCapturesOk returns a tuple with the MotionCaptures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetMotionCapturesOk() ([]FacialSimilarityReportMedia, bool) {
	if o == nil || IsNil(o.MotionCaptures) {
		return nil, false
	}
	return o.MotionCaptures, true
}

// HasMotionCaptures returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasMotionCaptures() bool {
	if o != nil && !IsNil(o.MotionCaptures) {
		return true
	}

	return false
}

// SetMotionCaptures gets a reference to the given []FacialSimilarityReportMedia and assigns it to the MotionCaptures field.
func (o *WatchlistStandardReport) SetMotionCaptures(v []FacialSimilarityReportMedia) {
	o.MotionCaptures = v
}

// GetName returns the Name field value
func (o *WatchlistStandardReport) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WatchlistStandardReport) SetName(v string) {
	o.Name = v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetBreakdown() WatchlistStandardBreakdown {
	if o == nil || IsNil(o.Breakdown) {
		var ret WatchlistStandardBreakdown
		return ret
	}
	return *o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetBreakdownOk() (*WatchlistStandardBreakdown, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given WatchlistStandardBreakdown and assigns it to the Breakdown field.
func (o *WatchlistStandardReport) SetBreakdown(v WatchlistStandardBreakdown) {
	o.Breakdown = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *WatchlistStandardReport) GetProperties() WatchlistStandardProperties {
	if o == nil || IsNil(o.Properties) {
		var ret WatchlistStandardProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchlistStandardReport) GetPropertiesOk() (*WatchlistStandardProperties, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *WatchlistStandardReport) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given WatchlistStandardProperties and assigns it to the Properties field.
func (o *WatchlistStandardReport) SetProperties(v WatchlistStandardProperties) {
	o.Properties = &v
}

func (o WatchlistStandardReport) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WatchlistStandardReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ReadOnly != nil {
		toSerialize["readOnly"] = o.ReadOnly
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.SubResult) {
		toSerialize["sub_result"] = o.SubResult
	}
	if !IsNil(o.CheckId) {
		toSerialize["check_id"] = o.CheckId
	}
	if !IsNil(o.Documents) {
		toSerialize["documents"] = o.Documents
	}
	if !IsNil(o.IdPhotos) {
		toSerialize["id_photos"] = o.IdPhotos
	}
	if !IsNil(o.LivePhotos) {
		toSerialize["live_photos"] = o.LivePhotos
	}
	if !IsNil(o.LiveVideos) {
		toSerialize["live_videos"] = o.LiveVideos
	}
	if !IsNil(o.MotionCaptures) {
		toSerialize["motion_captures"] = o.MotionCaptures
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Breakdown) {
		toSerialize["breakdown"] = o.Breakdown
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

func (o *WatchlistStandardReport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWatchlistStandardReport := _WatchlistStandardReport{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// decoder.DisallowUnknownFields() - disabled to allow unknown fields from Onfido API
	err = decoder.Decode(&varWatchlistStandardReport)

	if err != nil {
		return err
	}

	*o = WatchlistStandardReport(varWatchlistStandardReport)

	return err
}

type NullableWatchlistStandardReport struct {
	value *WatchlistStandardReport
	isSet bool
}

func (v NullableWatchlistStandardReport) Get() *WatchlistStandardReport {
	return v.value
}

func (v *NullableWatchlistStandardReport) Set(val *WatchlistStandardReport) {
	v.value = val
	v.isSet = true
}

func (v NullableWatchlistStandardReport) IsSet() bool {
	return v.isSet
}

func (v *NullableWatchlistStandardReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWatchlistStandardReport(val *WatchlistStandardReport) *NullableWatchlistStandardReport {
	return &NullableWatchlistStandardReport{value: val, isSet: true}
}

func (v NullableWatchlistStandardReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWatchlistStandardReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
