/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the RightToWorkBreakdownDataValidation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RightToWorkBreakdownDataValidation{}

// RightToWorkBreakdownDataValidation Asserts whether algorithmically validatable elements are correct.
type RightToWorkBreakdownDataValidation struct {
	Result    *string                                      `json:"result,omitempty"`
	Breakdown *RightToWorkBreakdownDataValidationBreakdown `json:"breakdown,omitempty"`
}

// NewRightToWorkBreakdownDataValidation instantiates a new RightToWorkBreakdownDataValidation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRightToWorkBreakdownDataValidation() *RightToWorkBreakdownDataValidation {
	this := RightToWorkBreakdownDataValidation{}
	return &this
}

// NewRightToWorkBreakdownDataValidationWithDefaults instantiates a new RightToWorkBreakdownDataValidation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRightToWorkBreakdownDataValidationWithDefaults() *RightToWorkBreakdownDataValidation {
	this := RightToWorkBreakdownDataValidation{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *RightToWorkBreakdownDataValidation) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RightToWorkBreakdownDataValidation) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *RightToWorkBreakdownDataValidation) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *RightToWorkBreakdownDataValidation) SetResult(v string) {
	o.Result = &v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *RightToWorkBreakdownDataValidation) GetBreakdown() RightToWorkBreakdownDataValidationBreakdown {
	if o == nil || IsNil(o.Breakdown) {
		var ret RightToWorkBreakdownDataValidationBreakdown
		return ret
	}
	return *o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RightToWorkBreakdownDataValidation) GetBreakdownOk() (*RightToWorkBreakdownDataValidationBreakdown, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *RightToWorkBreakdownDataValidation) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given RightToWorkBreakdownDataValidationBreakdown and assigns it to the Breakdown field.
func (o *RightToWorkBreakdownDataValidation) SetBreakdown(v RightToWorkBreakdownDataValidationBreakdown) {
	o.Breakdown = &v
}

func (o RightToWorkBreakdownDataValidation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RightToWorkBreakdownDataValidation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Breakdown) {
		toSerialize["breakdown"] = o.Breakdown
	}
	return toSerialize, nil
}

type NullableRightToWorkBreakdownDataValidation struct {
	value *RightToWorkBreakdownDataValidation
	isSet bool
}

func (v NullableRightToWorkBreakdownDataValidation) Get() *RightToWorkBreakdownDataValidation {
	return v.value
}

func (v *NullableRightToWorkBreakdownDataValidation) Set(val *RightToWorkBreakdownDataValidation) {
	v.value = val
	v.isSet = true
}

func (v NullableRightToWorkBreakdownDataValidation) IsSet() bool {
	return v.isSet
}

func (v *NullableRightToWorkBreakdownDataValidation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRightToWorkBreakdownDataValidation(val *RightToWorkBreakdownDataValidation) *NullableRightToWorkBreakdownDataValidation {
	return &NullableRightToWorkBreakdownDataValidation{value: val, isSet: true}
}

func (v NullableRightToWorkBreakdownDataValidation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRightToWorkBreakdownDataValidation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
