/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the IdentityEnhancedBreakdownAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentityEnhancedBreakdownAddress{}

// IdentityEnhancedBreakdownAddress Asserts if the applicant's address matches any sources.
type IdentityEnhancedBreakdownAddress struct {
	Result    *string                                    `json:"result,omitempty"`
	Breakdown *IdentityEnhancedBreakdownAddressBreakdown `json:"breakdown,omitempty"`
}

// NewIdentityEnhancedBreakdownAddress instantiates a new IdentityEnhancedBreakdownAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityEnhancedBreakdownAddress() *IdentityEnhancedBreakdownAddress {
	this := IdentityEnhancedBreakdownAddress{}
	return &this
}

// NewIdentityEnhancedBreakdownAddressWithDefaults instantiates a new IdentityEnhancedBreakdownAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityEnhancedBreakdownAddressWithDefaults() *IdentityEnhancedBreakdownAddress {
	this := IdentityEnhancedBreakdownAddress{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *IdentityEnhancedBreakdownAddress) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityEnhancedBreakdownAddress) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *IdentityEnhancedBreakdownAddress) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *IdentityEnhancedBreakdownAddress) SetResult(v string) {
	o.Result = &v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *IdentityEnhancedBreakdownAddress) GetBreakdown() IdentityEnhancedBreakdownAddressBreakdown {
	if o == nil || IsNil(o.Breakdown) {
		var ret IdentityEnhancedBreakdownAddressBreakdown
		return ret
	}
	return *o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityEnhancedBreakdownAddress) GetBreakdownOk() (*IdentityEnhancedBreakdownAddressBreakdown, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *IdentityEnhancedBreakdownAddress) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given IdentityEnhancedBreakdownAddressBreakdown and assigns it to the Breakdown field.
func (o *IdentityEnhancedBreakdownAddress) SetBreakdown(v IdentityEnhancedBreakdownAddressBreakdown) {
	o.Breakdown = &v
}

func (o IdentityEnhancedBreakdownAddress) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentityEnhancedBreakdownAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Breakdown) {
		toSerialize["breakdown"] = o.Breakdown
	}
	return toSerialize, nil
}

type NullableIdentityEnhancedBreakdownAddress struct {
	value *IdentityEnhancedBreakdownAddress
	isSet bool
}

func (v NullableIdentityEnhancedBreakdownAddress) Get() *IdentityEnhancedBreakdownAddress {
	return v.value
}

func (v *NullableIdentityEnhancedBreakdownAddress) Set(val *IdentityEnhancedBreakdownAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityEnhancedBreakdownAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityEnhancedBreakdownAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityEnhancedBreakdownAddress(val *IdentityEnhancedBreakdownAddress) *NullableIdentityEnhancedBreakdownAddress {
	return &NullableIdentityEnhancedBreakdownAddress{value: val, isSet: true}
}

func (v NullableIdentityEnhancedBreakdownAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityEnhancedBreakdownAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
