/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the FacialSimilarityPhotoBreakdownFaceComparison type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FacialSimilarityPhotoBreakdownFaceComparison{}

// FacialSimilarityPhotoBreakdownFaceComparison Asserts whether the face in the document matches the face in the live photo.
type FacialSimilarityPhotoBreakdownFaceComparison struct {
	Result    *string                                                `json:"result,omitempty"`
	Breakdown *FacialSimilarityPhotoBreakdownFaceComparisonBreakdown `json:"breakdown,omitempty"`
}

// NewFacialSimilarityPhotoBreakdownFaceComparison instantiates a new FacialSimilarityPhotoBreakdownFaceComparison object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFacialSimilarityPhotoBreakdownFaceComparison() *FacialSimilarityPhotoBreakdownFaceComparison {
	this := FacialSimilarityPhotoBreakdownFaceComparison{}
	return &this
}

// NewFacialSimilarityPhotoBreakdownFaceComparisonWithDefaults instantiates a new FacialSimilarityPhotoBreakdownFaceComparison object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFacialSimilarityPhotoBreakdownFaceComparisonWithDefaults() *FacialSimilarityPhotoBreakdownFaceComparison {
	this := FacialSimilarityPhotoBreakdownFaceComparison{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *FacialSimilarityPhotoBreakdownFaceComparison) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityPhotoBreakdownFaceComparison) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *FacialSimilarityPhotoBreakdownFaceComparison) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *FacialSimilarityPhotoBreakdownFaceComparison) SetResult(v string) {
	o.Result = &v
}

// GetBreakdown returns the Breakdown field value if set, zero value otherwise.
func (o *FacialSimilarityPhotoBreakdownFaceComparison) GetBreakdown() FacialSimilarityPhotoBreakdownFaceComparisonBreakdown {
	if o == nil || IsNil(o.Breakdown) {
		var ret FacialSimilarityPhotoBreakdownFaceComparisonBreakdown
		return ret
	}
	return *o.Breakdown
}

// GetBreakdownOk returns a tuple with the Breakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FacialSimilarityPhotoBreakdownFaceComparison) GetBreakdownOk() (*FacialSimilarityPhotoBreakdownFaceComparisonBreakdown, bool) {
	if o == nil || IsNil(o.Breakdown) {
		return nil, false
	}
	return o.Breakdown, true
}

// HasBreakdown returns a boolean if a field has been set.
func (o *FacialSimilarityPhotoBreakdownFaceComparison) HasBreakdown() bool {
	if o != nil && !IsNil(o.Breakdown) {
		return true
	}

	return false
}

// SetBreakdown gets a reference to the given FacialSimilarityPhotoBreakdownFaceComparisonBreakdown and assigns it to the Breakdown field.
func (o *FacialSimilarityPhotoBreakdownFaceComparison) SetBreakdown(v FacialSimilarityPhotoBreakdownFaceComparisonBreakdown) {
	o.Breakdown = &v
}

func (o FacialSimilarityPhotoBreakdownFaceComparison) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FacialSimilarityPhotoBreakdownFaceComparison) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Breakdown) {
		toSerialize["breakdown"] = o.Breakdown
	}
	return toSerialize, nil
}

type NullableFacialSimilarityPhotoBreakdownFaceComparison struct {
	value *FacialSimilarityPhotoBreakdownFaceComparison
	isSet bool
}

func (v NullableFacialSimilarityPhotoBreakdownFaceComparison) Get() *FacialSimilarityPhotoBreakdownFaceComparison {
	return v.value
}

func (v *NullableFacialSimilarityPhotoBreakdownFaceComparison) Set(val *FacialSimilarityPhotoBreakdownFaceComparison) {
	v.value = val
	v.isSet = true
}

func (v NullableFacialSimilarityPhotoBreakdownFaceComparison) IsSet() bool {
	return v.isSet
}

func (v *NullableFacialSimilarityPhotoBreakdownFaceComparison) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFacialSimilarityPhotoBreakdownFaceComparison(val *FacialSimilarityPhotoBreakdownFaceComparison) *NullableFacialSimilarityPhotoBreakdownFaceComparison {
	return &NullableFacialSimilarityPhotoBreakdownFaceComparison{value: val, isSet: true}
}

func (v NullableFacialSimilarityPhotoBreakdownFaceComparison) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFacialSimilarityPhotoBreakdownFaceComparison) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
