/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity{}

// PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity Asserts whether the live photo is trustworthy - i.e. not digitally tampered, from a fake webcam, or from other dubious sources.
type PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity struct {
	Result     *string           `json:"result,omitempty"`
	Properties *PhotoAutoReasons `json:"properties,omitempty"`
}

// NewPhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity instantiates a new PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity() *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity {
	this := PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity{}
	return &this
}

// NewPhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrityWithDefaults instantiates a new PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrityWithDefaults() *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity {
	this := PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) SetResult(v string) {
	o.Result = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) GetProperties() PhotoAutoReasons {
	if o == nil || IsNil(o.Properties) {
		var ret PhotoAutoReasons
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) GetPropertiesOk() (*PhotoAutoReasons, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given PhotoAutoReasons and assigns it to the Properties field.
func (o *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) SetProperties(v PhotoAutoReasons) {
	o.Properties = &v
}

func (o PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

type NullablePhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity struct {
	value *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity
	isSet bool
}

func (v NullablePhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) Get() *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity {
	return v.value
}

func (v *NullablePhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) Set(val *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) {
	v.value = val
	v.isSet = true
}

func (v NullablePhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) IsSet() bool {
	return v.isSet
}

func (v *NullablePhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity(val *PhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) *NullablePhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity {
	return &NullablePhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity{value: val, isSet: true}
}

func (v NullablePhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePhotoFullyAutoBreakdownImageIntegrityBreakdownSourceIntegrity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
