/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the DeviceIntelligencePropertiesIp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceIntelligencePropertiesIp{}

// DeviceIntelligencePropertiesIp struct for DeviceIntelligencePropertiesIp
type DeviceIntelligencePropertiesIp struct {
	// The IP address that uploaded the media.
	Address *string `json:"address,omitempty"`
	// The type of IP address.
	Type *string `json:"type,omitempty"`
	// VPN detection result.
	VpnDetection *string `json:"vpn_detection,omitempty"`
	// Proxy detection result.
	ProxyDetection *string `json:"proxy_detection,omitempty"`
}

// NewDeviceIntelligencePropertiesIp instantiates a new DeviceIntelligencePropertiesIp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceIntelligencePropertiesIp() *DeviceIntelligencePropertiesIp {
	this := DeviceIntelligencePropertiesIp{}
	return &this
}

// NewDeviceIntelligencePropertiesIpWithDefaults instantiates a new DeviceIntelligencePropertiesIp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceIntelligencePropertiesIpWithDefaults() *DeviceIntelligencePropertiesIp {
	this := DeviceIntelligencePropertiesIp{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *DeviceIntelligencePropertiesIp) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligencePropertiesIp) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *DeviceIntelligencePropertiesIp) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *DeviceIntelligencePropertiesIp) SetAddress(v string) {
	o.Address = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DeviceIntelligencePropertiesIp) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligencePropertiesIp) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DeviceIntelligencePropertiesIp) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *DeviceIntelligencePropertiesIp) SetType(v string) {
	o.Type = &v
}

// GetVpnDetection returns the VpnDetection field value if set, zero value otherwise.
func (o *DeviceIntelligencePropertiesIp) GetVpnDetection() string {
	if o == nil || IsNil(o.VpnDetection) {
		var ret string
		return ret
	}
	return *o.VpnDetection
}

// GetVpnDetectionOk returns a tuple with the VpnDetection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligencePropertiesIp) GetVpnDetectionOk() (*string, bool) {
	if o == nil || IsNil(o.VpnDetection) {
		return nil, false
	}
	return o.VpnDetection, true
}

// HasVpnDetection returns a boolean if a field has been set.
func (o *DeviceIntelligencePropertiesIp) HasVpnDetection() bool {
	if o != nil && !IsNil(o.VpnDetection) {
		return true
	}

	return false
}

// SetVpnDetection gets a reference to the given string and assigns it to the VpnDetection field.
func (o *DeviceIntelligencePropertiesIp) SetVpnDetection(v string) {
	o.VpnDetection = &v
}

// GetProxyDetection returns the ProxyDetection field value if set, zero value otherwise.
func (o *DeviceIntelligencePropertiesIp) GetProxyDetection() string {
	if o == nil || IsNil(o.ProxyDetection) {
		var ret string
		return ret
	}
	return *o.ProxyDetection
}

// GetProxyDetectionOk returns a tuple with the ProxyDetection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligencePropertiesIp) GetProxyDetectionOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyDetection) {
		return nil, false
	}
	return o.ProxyDetection, true
}

// HasProxyDetection returns a boolean if a field has been set.
func (o *DeviceIntelligencePropertiesIp) HasProxyDetection() bool {
	if o != nil && !IsNil(o.ProxyDetection) {
		return true
	}

	return false
}

// SetProxyDetection gets a reference to the given string and assigns it to the ProxyDetection field.
func (o *DeviceIntelligencePropertiesIp) SetProxyDetection(v string) {
	o.ProxyDetection = &v
}

func (o DeviceIntelligencePropertiesIp) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceIntelligencePropertiesIp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.VpnDetection) {
		toSerialize["vpn_detection"] = o.VpnDetection
	}
	if !IsNil(o.ProxyDetection) {
		toSerialize["proxy_detection"] = o.ProxyDetection
	}
	return toSerialize, nil
}

type NullableDeviceIntelligencePropertiesIp struct {
	value *DeviceIntelligencePropertiesIp
	isSet bool
}

func (v NullableDeviceIntelligencePropertiesIp) Get() *DeviceIntelligencePropertiesIp {
	return v.value
}

func (v *NullableDeviceIntelligencePropertiesIp) Set(val *DeviceIntelligencePropertiesIp) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceIntelligencePropertiesIp) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceIntelligencePropertiesIp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceIntelligencePropertiesIp(val *DeviceIntelligencePropertiesIp) *NullableDeviceIntelligencePropertiesIp {
	return &NullableDeviceIntelligencePropertiesIp{value: val, isSet: true}
}

func (v NullableDeviceIntelligencePropertiesIp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceIntelligencePropertiesIp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
