/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the KnownFacesPropertiesMatchesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnownFacesPropertiesMatchesInner{}

// KnownFacesPropertiesMatchesInner struct for KnownFacesPropertiesMatchesInner
type KnownFacesPropertiesMatchesInner struct {
	// The applicant ID of the matched applicant.
	ApplicantId *string `json:"applicant_id,omitempty"`
	// A floating point number between 0 and 1 that expresses how similar the two faces are, where 1 is a perfect match.
	Score *float32 `json:"score,omitempty"`
	// The corresponding UUID for the media type.
	MediaId *string `json:"media_id,omitempty"`
	// The media type (for example live_photos or live_videos).
	MediaType *string `json:"media_type,omitempty"`
	// Indicates if match is suspected based on fuzzy name matching feature. Dependent on feature being active for account, otherwise defaults to true.
	Suspected *bool `json:"suspected,omitempty"`
}

// NewKnownFacesPropertiesMatchesInner instantiates a new KnownFacesPropertiesMatchesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnownFacesPropertiesMatchesInner() *KnownFacesPropertiesMatchesInner {
	this := KnownFacesPropertiesMatchesInner{}
	return &this
}

// NewKnownFacesPropertiesMatchesInnerWithDefaults instantiates a new KnownFacesPropertiesMatchesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnownFacesPropertiesMatchesInnerWithDefaults() *KnownFacesPropertiesMatchesInner {
	this := KnownFacesPropertiesMatchesInner{}
	return &this
}

// GetApplicantId returns the ApplicantId field value if set, zero value otherwise.
func (o *KnownFacesPropertiesMatchesInner) GetApplicantId() string {
	if o == nil || IsNil(o.ApplicantId) {
		var ret string
		return ret
	}
	return *o.ApplicantId
}

// GetApplicantIdOk returns a tuple with the ApplicantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnownFacesPropertiesMatchesInner) GetApplicantIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicantId) {
		return nil, false
	}
	return o.ApplicantId, true
}

// HasApplicantId returns a boolean if a field has been set.
func (o *KnownFacesPropertiesMatchesInner) HasApplicantId() bool {
	if o != nil && !IsNil(o.ApplicantId) {
		return true
	}

	return false
}

// SetApplicantId gets a reference to the given string and assigns it to the ApplicantId field.
func (o *KnownFacesPropertiesMatchesInner) SetApplicantId(v string) {
	o.ApplicantId = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *KnownFacesPropertiesMatchesInner) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnownFacesPropertiesMatchesInner) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *KnownFacesPropertiesMatchesInner) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *KnownFacesPropertiesMatchesInner) SetScore(v float32) {
	o.Score = &v
}

// GetMediaId returns the MediaId field value if set, zero value otherwise.
func (o *KnownFacesPropertiesMatchesInner) GetMediaId() string {
	if o == nil || IsNil(o.MediaId) {
		var ret string
		return ret
	}
	return *o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnownFacesPropertiesMatchesInner) GetMediaIdOk() (*string, bool) {
	if o == nil || IsNil(o.MediaId) {
		return nil, false
	}
	return o.MediaId, true
}

// HasMediaId returns a boolean if a field has been set.
func (o *KnownFacesPropertiesMatchesInner) HasMediaId() bool {
	if o != nil && !IsNil(o.MediaId) {
		return true
	}

	return false
}

// SetMediaId gets a reference to the given string and assigns it to the MediaId field.
func (o *KnownFacesPropertiesMatchesInner) SetMediaId(v string) {
	o.MediaId = &v
}

// GetMediaType returns the MediaType field value if set, zero value otherwise.
func (o *KnownFacesPropertiesMatchesInner) GetMediaType() string {
	if o == nil || IsNil(o.MediaType) {
		var ret string
		return ret
	}
	return *o.MediaType
}

// GetMediaTypeOk returns a tuple with the MediaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnownFacesPropertiesMatchesInner) GetMediaTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MediaType) {
		return nil, false
	}
	return o.MediaType, true
}

// HasMediaType returns a boolean if a field has been set.
func (o *KnownFacesPropertiesMatchesInner) HasMediaType() bool {
	if o != nil && !IsNil(o.MediaType) {
		return true
	}

	return false
}

// SetMediaType gets a reference to the given string and assigns it to the MediaType field.
func (o *KnownFacesPropertiesMatchesInner) SetMediaType(v string) {
	o.MediaType = &v
}

// GetSuspected returns the Suspected field value if set, zero value otherwise.
func (o *KnownFacesPropertiesMatchesInner) GetSuspected() bool {
	if o == nil || IsNil(o.Suspected) {
		var ret bool
		return ret
	}
	return *o.Suspected
}

// GetSuspectedOk returns a tuple with the Suspected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnownFacesPropertiesMatchesInner) GetSuspectedOk() (*bool, bool) {
	if o == nil || IsNil(o.Suspected) {
		return nil, false
	}
	return o.Suspected, true
}

// HasSuspected returns a boolean if a field has been set.
func (o *KnownFacesPropertiesMatchesInner) HasSuspected() bool {
	if o != nil && !IsNil(o.Suspected) {
		return true
	}

	return false
}

// SetSuspected gets a reference to the given bool and assigns it to the Suspected field.
func (o *KnownFacesPropertiesMatchesInner) SetSuspected(v bool) {
	o.Suspected = &v
}

func (o KnownFacesPropertiesMatchesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnownFacesPropertiesMatchesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApplicantId) {
		toSerialize["applicant_id"] = o.ApplicantId
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !IsNil(o.MediaId) {
		toSerialize["media_id"] = o.MediaId
	}
	if !IsNil(o.MediaType) {
		toSerialize["media_type"] = o.MediaType
	}
	if !IsNil(o.Suspected) {
		toSerialize["suspected"] = o.Suspected
	}
	return toSerialize, nil
}

type NullableKnownFacesPropertiesMatchesInner struct {
	value *KnownFacesPropertiesMatchesInner
	isSet bool
}

func (v NullableKnownFacesPropertiesMatchesInner) Get() *KnownFacesPropertiesMatchesInner {
	return v.value
}

func (v *NullableKnownFacesPropertiesMatchesInner) Set(val *KnownFacesPropertiesMatchesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableKnownFacesPropertiesMatchesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableKnownFacesPropertiesMatchesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnownFacesPropertiesMatchesInner(val *KnownFacesPropertiesMatchesInner) *NullableKnownFacesPropertiesMatchesInner {
	return &NullableKnownFacesPropertiesMatchesInner{value: val, isSet: true}
}

func (v NullableKnownFacesPropertiesMatchesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnownFacesPropertiesMatchesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
