/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality{}

// DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality Asserts if the document was of enough quality to be able to perform a fraud inspection.
type DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality struct {
	Result     *string             `json:"result,omitempty"`
	Properties *DocumentCDQReasons `json:"properties,omitempty"`
}

// NewDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality instantiates a new DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality() *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality {
	this := DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality{}
	return &this
}

// NewDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQualityWithDefaults instantiates a new DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQualityWithDefaults() *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality {
	this := DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) SetResult(v string) {
	o.Result = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) GetProperties() DocumentCDQReasons {
	if o == nil || IsNil(o.Properties) {
		var ret DocumentCDQReasons
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) GetPropertiesOk() (*DocumentCDQReasons, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given DocumentCDQReasons and assigns it to the Properties field.
func (o *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) SetProperties(v DocumentCDQReasons) {
	o.Properties = &v
}

func (o DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

type NullableDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality struct {
	value *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality
	isSet bool
}

func (v NullableDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) Get() *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality {
	return v.value
}

func (v *NullableDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) Set(val *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality(val *DocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) *NullableDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality {
	return &NullableDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality{value: val, isSet: true}
}

func (v NullableDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentBreakdownImageIntegrityBreakdownConclusiveDocumentQuality) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
