/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the DeviceIntelligenceBreakdownDeviceBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceIntelligenceBreakdownDeviceBreakdown{}

// DeviceIntelligenceBreakdownDeviceBreakdown struct for DeviceIntelligenceBreakdownDeviceBreakdown
type DeviceIntelligenceBreakdownDeviceBreakdown struct {
	ApplicationAuthenticity *DocumentBreakdownDataComparisonBreakdownIssuingCountry `json:"application_authenticity,omitempty"`
	DeviceIntegrity         *DocumentBreakdownDataComparisonBreakdownIssuingCountry `json:"device_integrity,omitempty"`
	DeviceReputation        *DocumentBreakdownDataComparisonBreakdownIssuingCountry `json:"device_reputation,omitempty"`
}

// NewDeviceIntelligenceBreakdownDeviceBreakdown instantiates a new DeviceIntelligenceBreakdownDeviceBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceIntelligenceBreakdownDeviceBreakdown() *DeviceIntelligenceBreakdownDeviceBreakdown {
	this := DeviceIntelligenceBreakdownDeviceBreakdown{}
	return &this
}

// NewDeviceIntelligenceBreakdownDeviceBreakdownWithDefaults instantiates a new DeviceIntelligenceBreakdownDeviceBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceIntelligenceBreakdownDeviceBreakdownWithDefaults() *DeviceIntelligenceBreakdownDeviceBreakdown {
	this := DeviceIntelligenceBreakdownDeviceBreakdown{}
	return &this
}

// GetApplicationAuthenticity returns the ApplicationAuthenticity field value if set, zero value otherwise.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) GetApplicationAuthenticity() DocumentBreakdownDataComparisonBreakdownIssuingCountry {
	if o == nil || IsNil(o.ApplicationAuthenticity) {
		var ret DocumentBreakdownDataComparisonBreakdownIssuingCountry
		return ret
	}
	return *o.ApplicationAuthenticity
}

// GetApplicationAuthenticityOk returns a tuple with the ApplicationAuthenticity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) GetApplicationAuthenticityOk() (*DocumentBreakdownDataComparisonBreakdownIssuingCountry, bool) {
	if o == nil || IsNil(o.ApplicationAuthenticity) {
		return nil, false
	}
	return o.ApplicationAuthenticity, true
}

// HasApplicationAuthenticity returns a boolean if a field has been set.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) HasApplicationAuthenticity() bool {
	if o != nil && !IsNil(o.ApplicationAuthenticity) {
		return true
	}

	return false
}

// SetApplicationAuthenticity gets a reference to the given DocumentBreakdownDataComparisonBreakdownIssuingCountry and assigns it to the ApplicationAuthenticity field.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) SetApplicationAuthenticity(v DocumentBreakdownDataComparisonBreakdownIssuingCountry) {
	o.ApplicationAuthenticity = &v
}

// GetDeviceIntegrity returns the DeviceIntegrity field value if set, zero value otherwise.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) GetDeviceIntegrity() DocumentBreakdownDataComparisonBreakdownIssuingCountry {
	if o == nil || IsNil(o.DeviceIntegrity) {
		var ret DocumentBreakdownDataComparisonBreakdownIssuingCountry
		return ret
	}
	return *o.DeviceIntegrity
}

// GetDeviceIntegrityOk returns a tuple with the DeviceIntegrity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) GetDeviceIntegrityOk() (*DocumentBreakdownDataComparisonBreakdownIssuingCountry, bool) {
	if o == nil || IsNil(o.DeviceIntegrity) {
		return nil, false
	}
	return o.DeviceIntegrity, true
}

// HasDeviceIntegrity returns a boolean if a field has been set.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) HasDeviceIntegrity() bool {
	if o != nil && !IsNil(o.DeviceIntegrity) {
		return true
	}

	return false
}

// SetDeviceIntegrity gets a reference to the given DocumentBreakdownDataComparisonBreakdownIssuingCountry and assigns it to the DeviceIntegrity field.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) SetDeviceIntegrity(v DocumentBreakdownDataComparisonBreakdownIssuingCountry) {
	o.DeviceIntegrity = &v
}

// GetDeviceReputation returns the DeviceReputation field value if set, zero value otherwise.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) GetDeviceReputation() DocumentBreakdownDataComparisonBreakdownIssuingCountry {
	if o == nil || IsNil(o.DeviceReputation) {
		var ret DocumentBreakdownDataComparisonBreakdownIssuingCountry
		return ret
	}
	return *o.DeviceReputation
}

// GetDeviceReputationOk returns a tuple with the DeviceReputation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) GetDeviceReputationOk() (*DocumentBreakdownDataComparisonBreakdownIssuingCountry, bool) {
	if o == nil || IsNil(o.DeviceReputation) {
		return nil, false
	}
	return o.DeviceReputation, true
}

// HasDeviceReputation returns a boolean if a field has been set.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) HasDeviceReputation() bool {
	if o != nil && !IsNil(o.DeviceReputation) {
		return true
	}

	return false
}

// SetDeviceReputation gets a reference to the given DocumentBreakdownDataComparisonBreakdownIssuingCountry and assigns it to the DeviceReputation field.
func (o *DeviceIntelligenceBreakdownDeviceBreakdown) SetDeviceReputation(v DocumentBreakdownDataComparisonBreakdownIssuingCountry) {
	o.DeviceReputation = &v
}

func (o DeviceIntelligenceBreakdownDeviceBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceIntelligenceBreakdownDeviceBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApplicationAuthenticity) {
		toSerialize["application_authenticity"] = o.ApplicationAuthenticity
	}
	if !IsNil(o.DeviceIntegrity) {
		toSerialize["device_integrity"] = o.DeviceIntegrity
	}
	if !IsNil(o.DeviceReputation) {
		toSerialize["device_reputation"] = o.DeviceReputation
	}
	return toSerialize, nil
}

type NullableDeviceIntelligenceBreakdownDeviceBreakdown struct {
	value *DeviceIntelligenceBreakdownDeviceBreakdown
	isSet bool
}

func (v NullableDeviceIntelligenceBreakdownDeviceBreakdown) Get() *DeviceIntelligenceBreakdownDeviceBreakdown {
	return v.value
}

func (v *NullableDeviceIntelligenceBreakdownDeviceBreakdown) Set(val *DeviceIntelligenceBreakdownDeviceBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceIntelligenceBreakdownDeviceBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceIntelligenceBreakdownDeviceBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceIntelligenceBreakdownDeviceBreakdown(val *DeviceIntelligenceBreakdownDeviceBreakdown) *NullableDeviceIntelligenceBreakdownDeviceBreakdown {
	return &NullableDeviceIntelligenceBreakdownDeviceBreakdown{value: val, isSet: true}
}

func (v NullableDeviceIntelligenceBreakdownDeviceBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceIntelligenceBreakdownDeviceBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
