/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the DeviceIntelligenceBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceIntelligenceBreakdown{}

// DeviceIntelligenceBreakdown struct for DeviceIntelligenceBreakdown
type DeviceIntelligenceBreakdown struct {
	Device *DeviceIntelligenceBreakdownDevice `json:"device,omitempty"`
}

// NewDeviceIntelligenceBreakdown instantiates a new DeviceIntelligenceBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceIntelligenceBreakdown() *DeviceIntelligenceBreakdown {
	this := DeviceIntelligenceBreakdown{}
	return &this
}

// NewDeviceIntelligenceBreakdownWithDefaults instantiates a new DeviceIntelligenceBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceIntelligenceBreakdownWithDefaults() *DeviceIntelligenceBreakdown {
	this := DeviceIntelligenceBreakdown{}
	return &this
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *DeviceIntelligenceBreakdown) GetDevice() DeviceIntelligenceBreakdownDevice {
	if o == nil || IsNil(o.Device) {
		var ret DeviceIntelligenceBreakdownDevice
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligenceBreakdown) GetDeviceOk() (*DeviceIntelligenceBreakdownDevice, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *DeviceIntelligenceBreakdown) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given DeviceIntelligenceBreakdownDevice and assigns it to the Device field.
func (o *DeviceIntelligenceBreakdown) SetDevice(v DeviceIntelligenceBreakdownDevice) {
	o.Device = &v
}

func (o DeviceIntelligenceBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceIntelligenceBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	return toSerialize, nil
}

type NullableDeviceIntelligenceBreakdown struct {
	value *DeviceIntelligenceBreakdown
	isSet bool
}

func (v NullableDeviceIntelligenceBreakdown) Get() *DeviceIntelligenceBreakdown {
	return v.value
}

func (v *NullableDeviceIntelligenceBreakdown) Set(val *DeviceIntelligenceBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceIntelligenceBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceIntelligenceBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceIntelligenceBreakdown(val *DeviceIntelligenceBreakdown) *NullableDeviceIntelligenceBreakdown {
	return &NullableDeviceIntelligenceBreakdown{value: val, isSet: true}
}

func (v NullableDeviceIntelligenceBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceIntelligenceBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
