/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the IdentityEnhancedBreakdownSourcesBreakdownTotalSources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentityEnhancedBreakdownSourcesBreakdownTotalSources{}

// IdentityEnhancedBreakdownSourcesBreakdownTotalSources The number of sources which produced a match to applicant details.
type IdentityEnhancedBreakdownSourcesBreakdownTotalSources struct {
	Result     *string                                                          `json:"result,omitempty"`
	Properties *IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties `json:"properties,omitempty"`
}

// NewIdentityEnhancedBreakdownSourcesBreakdownTotalSources instantiates a new IdentityEnhancedBreakdownSourcesBreakdownTotalSources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityEnhancedBreakdownSourcesBreakdownTotalSources() *IdentityEnhancedBreakdownSourcesBreakdownTotalSources {
	this := IdentityEnhancedBreakdownSourcesBreakdownTotalSources{}
	return &this
}

// NewIdentityEnhancedBreakdownSourcesBreakdownTotalSourcesWithDefaults instantiates a new IdentityEnhancedBreakdownSourcesBreakdownTotalSources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityEnhancedBreakdownSourcesBreakdownTotalSourcesWithDefaults() *IdentityEnhancedBreakdownSourcesBreakdownTotalSources {
	this := IdentityEnhancedBreakdownSourcesBreakdownTotalSources{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *IdentityEnhancedBreakdownSourcesBreakdownTotalSources) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityEnhancedBreakdownSourcesBreakdownTotalSources) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *IdentityEnhancedBreakdownSourcesBreakdownTotalSources) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *IdentityEnhancedBreakdownSourcesBreakdownTotalSources) SetResult(v string) {
	o.Result = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *IdentityEnhancedBreakdownSourcesBreakdownTotalSources) GetProperties() IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties {
	if o == nil || IsNil(o.Properties) {
		var ret IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityEnhancedBreakdownSourcesBreakdownTotalSources) GetPropertiesOk() (*IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *IdentityEnhancedBreakdownSourcesBreakdownTotalSources) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties and assigns it to the Properties field.
func (o *IdentityEnhancedBreakdownSourcesBreakdownTotalSources) SetProperties(v IdentityEnhancedBreakdownSourcesBreakdownTotalSourcesProperties) {
	o.Properties = &v
}

func (o IdentityEnhancedBreakdownSourcesBreakdownTotalSources) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentityEnhancedBreakdownSourcesBreakdownTotalSources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

type NullableIdentityEnhancedBreakdownSourcesBreakdownTotalSources struct {
	value *IdentityEnhancedBreakdownSourcesBreakdownTotalSources
	isSet bool
}

func (v NullableIdentityEnhancedBreakdownSourcesBreakdownTotalSources) Get() *IdentityEnhancedBreakdownSourcesBreakdownTotalSources {
	return v.value
}

func (v *NullableIdentityEnhancedBreakdownSourcesBreakdownTotalSources) Set(val *IdentityEnhancedBreakdownSourcesBreakdownTotalSources) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityEnhancedBreakdownSourcesBreakdownTotalSources) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityEnhancedBreakdownSourcesBreakdownTotalSources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityEnhancedBreakdownSourcesBreakdownTotalSources(val *IdentityEnhancedBreakdownSourcesBreakdownTotalSources) *NullableIdentityEnhancedBreakdownSourcesBreakdownTotalSources {
	return &NullableIdentityEnhancedBreakdownSourcesBreakdownTotalSources{value: val, isSet: true}
}

func (v NullableIdentityEnhancedBreakdownSourcesBreakdownTotalSources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityEnhancedBreakdownSourcesBreakdownTotalSources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
