/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the RightToWorkBreakdownDataValidationBreakdownDocumentNumbers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RightToWorkBreakdownDataValidationBreakdownDocumentNumbers{}

// RightToWorkBreakdownDataValidationBreakdownDocumentNumbers struct for RightToWorkBreakdownDataValidationBreakdownDocumentNumbers
type RightToWorkBreakdownDataValidationBreakdownDocumentNumbers struct {
	Result     *string                                                               `json:"result,omitempty"`
	Properties *RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties `json:"properties,omitempty"`
}

// NewRightToWorkBreakdownDataValidationBreakdownDocumentNumbers instantiates a new RightToWorkBreakdownDataValidationBreakdownDocumentNumbers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRightToWorkBreakdownDataValidationBreakdownDocumentNumbers() *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers {
	this := RightToWorkBreakdownDataValidationBreakdownDocumentNumbers{}
	return &this
}

// NewRightToWorkBreakdownDataValidationBreakdownDocumentNumbersWithDefaults instantiates a new RightToWorkBreakdownDataValidationBreakdownDocumentNumbers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRightToWorkBreakdownDataValidationBreakdownDocumentNumbersWithDefaults() *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers {
	this := RightToWorkBreakdownDataValidationBreakdownDocumentNumbers{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) SetResult(v string) {
	o.Result = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) GetProperties() RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties {
	if o == nil || IsNil(o.Properties) {
		var ret RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) GetPropertiesOk() (*RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties and assigns it to the Properties field.
func (o *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) SetProperties(v RightToWorkBreakdownDataValidationBreakdownDocumentNumbersProperties) {
	o.Properties = &v
}

func (o RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

type NullableRightToWorkBreakdownDataValidationBreakdownDocumentNumbers struct {
	value *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers
	isSet bool
}

func (v NullableRightToWorkBreakdownDataValidationBreakdownDocumentNumbers) Get() *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers {
	return v.value
}

func (v *NullableRightToWorkBreakdownDataValidationBreakdownDocumentNumbers) Set(val *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) {
	v.value = val
	v.isSet = true
}

func (v NullableRightToWorkBreakdownDataValidationBreakdownDocumentNumbers) IsSet() bool {
	return v.isSet
}

func (v *NullableRightToWorkBreakdownDataValidationBreakdownDocumentNumbers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRightToWorkBreakdownDataValidationBreakdownDocumentNumbers(val *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) *NullableRightToWorkBreakdownDataValidationBreakdownDocumentNumbers {
	return &NullableRightToWorkBreakdownDataValidationBreakdownDocumentNumbers{value: val, isSet: true}
}

func (v NullableRightToWorkBreakdownDataValidationBreakdownDocumentNumbers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRightToWorkBreakdownDataValidationBreakdownDocumentNumbers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
