/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the DeviceIntelligencePropertiesGeolocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceIntelligencePropertiesGeolocation{}

// DeviceIntelligencePropertiesGeolocation struct for DeviceIntelligencePropertiesGeolocation
type DeviceIntelligencePropertiesGeolocation struct {
	// City location of the IP address.
	City *string `json:"city,omitempty"`
	// Region location of the IP address.
	Region *string `json:"region,omitempty"`
	// Country location of the IP address in a three letter format.
	Country *string `json:"country,omitempty"`
}

// NewDeviceIntelligencePropertiesGeolocation instantiates a new DeviceIntelligencePropertiesGeolocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceIntelligencePropertiesGeolocation() *DeviceIntelligencePropertiesGeolocation {
	this := DeviceIntelligencePropertiesGeolocation{}
	return &this
}

// NewDeviceIntelligencePropertiesGeolocationWithDefaults instantiates a new DeviceIntelligencePropertiesGeolocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceIntelligencePropertiesGeolocationWithDefaults() *DeviceIntelligencePropertiesGeolocation {
	this := DeviceIntelligencePropertiesGeolocation{}
	return &this
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *DeviceIntelligencePropertiesGeolocation) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligencePropertiesGeolocation) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *DeviceIntelligencePropertiesGeolocation) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *DeviceIntelligencePropertiesGeolocation) SetCity(v string) {
	o.City = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *DeviceIntelligencePropertiesGeolocation) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligencePropertiesGeolocation) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *DeviceIntelligencePropertiesGeolocation) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *DeviceIntelligencePropertiesGeolocation) SetRegion(v string) {
	o.Region = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *DeviceIntelligencePropertiesGeolocation) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceIntelligencePropertiesGeolocation) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *DeviceIntelligencePropertiesGeolocation) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *DeviceIntelligencePropertiesGeolocation) SetCountry(v string) {
	o.Country = &v
}

func (o DeviceIntelligencePropertiesGeolocation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceIntelligencePropertiesGeolocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	return toSerialize, nil
}

type NullableDeviceIntelligencePropertiesGeolocation struct {
	value *DeviceIntelligencePropertiesGeolocation
	isSet bool
}

func (v NullableDeviceIntelligencePropertiesGeolocation) Get() *DeviceIntelligencePropertiesGeolocation {
	return v.value
}

func (v *NullableDeviceIntelligencePropertiesGeolocation) Set(val *DeviceIntelligencePropertiesGeolocation) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceIntelligencePropertiesGeolocation) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceIntelligencePropertiesGeolocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceIntelligencePropertiesGeolocation(val *DeviceIntelligencePropertiesGeolocation) *NullableDeviceIntelligencePropertiesGeolocation {
	return &NullableDeviceIntelligencePropertiesGeolocation{value: val, isSet: true}
}

func (v NullableDeviceIntelligencePropertiesGeolocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceIntelligencePropertiesGeolocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
