/*
Onfido API v3.6

The Onfido API is used to submit check requests.

API version: 3.6.0
Contact: engineering@onfido.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onfido_openapi

import (
	"encoding/json"
)

// checks if the RightToWorkBreakdownDataValidationBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RightToWorkBreakdownDataValidationBreakdown{}

// RightToWorkBreakdownDataValidationBreakdown struct for RightToWorkBreakdownDataValidationBreakdown
type RightToWorkBreakdownDataValidationBreakdown struct {
	Gender             *DocumentBreakdownDataComparisonBreakdownIssuingCountry     `json:"gender,omitempty"`
	DateOfBirth        *DocumentBreakdownDataComparisonBreakdownIssuingCountry     `json:"date_of_birth,omitempty"`
	DocumentNumbers    *RightToWorkBreakdownDataValidationBreakdownDocumentNumbers `json:"document_numbers,omitempty"`
	DocumentExpiration *DocumentBreakdownDataComparisonBreakdownIssuingCountry     `json:"document_expiration,omitempty"`
	ExpiryDate         *DocumentBreakdownDataComparisonBreakdownIssuingCountry     `json:"expiry_date,omitempty"`
	Mrz                *DocumentBreakdownDataComparisonBreakdownIssuingCountry     `json:"mrz,omitempty"`
}

// NewRightToWorkBreakdownDataValidationBreakdown instantiates a new RightToWorkBreakdownDataValidationBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRightToWorkBreakdownDataValidationBreakdown() *RightToWorkBreakdownDataValidationBreakdown {
	this := RightToWorkBreakdownDataValidationBreakdown{}
	return &this
}

// NewRightToWorkBreakdownDataValidationBreakdownWithDefaults instantiates a new RightToWorkBreakdownDataValidationBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRightToWorkBreakdownDataValidationBreakdownWithDefaults() *RightToWorkBreakdownDataValidationBreakdown {
	this := RightToWorkBreakdownDataValidationBreakdown{}
	return &this
}

// GetGender returns the Gender field value if set, zero value otherwise.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetGender() DocumentBreakdownDataComparisonBreakdownIssuingCountry {
	if o == nil || IsNil(o.Gender) {
		var ret DocumentBreakdownDataComparisonBreakdownIssuingCountry
		return ret
	}
	return *o.Gender
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetGenderOk() (*DocumentBreakdownDataComparisonBreakdownIssuingCountry, bool) {
	if o == nil || IsNil(o.Gender) {
		return nil, false
	}
	return o.Gender, true
}

// HasGender returns a boolean if a field has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) HasGender() bool {
	if o != nil && !IsNil(o.Gender) {
		return true
	}

	return false
}

// SetGender gets a reference to the given DocumentBreakdownDataComparisonBreakdownIssuingCountry and assigns it to the Gender field.
func (o *RightToWorkBreakdownDataValidationBreakdown) SetGender(v DocumentBreakdownDataComparisonBreakdownIssuingCountry) {
	o.Gender = &v
}

// GetDateOfBirth returns the DateOfBirth field value if set, zero value otherwise.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetDateOfBirth() DocumentBreakdownDataComparisonBreakdownIssuingCountry {
	if o == nil || IsNil(o.DateOfBirth) {
		var ret DocumentBreakdownDataComparisonBreakdownIssuingCountry
		return ret
	}
	return *o.DateOfBirth
}

// GetDateOfBirthOk returns a tuple with the DateOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetDateOfBirthOk() (*DocumentBreakdownDataComparisonBreakdownIssuingCountry, bool) {
	if o == nil || IsNil(o.DateOfBirth) {
		return nil, false
	}
	return o.DateOfBirth, true
}

// HasDateOfBirth returns a boolean if a field has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) HasDateOfBirth() bool {
	if o != nil && !IsNil(o.DateOfBirth) {
		return true
	}

	return false
}

// SetDateOfBirth gets a reference to the given DocumentBreakdownDataComparisonBreakdownIssuingCountry and assigns it to the DateOfBirth field.
func (o *RightToWorkBreakdownDataValidationBreakdown) SetDateOfBirth(v DocumentBreakdownDataComparisonBreakdownIssuingCountry) {
	o.DateOfBirth = &v
}

// GetDocumentNumbers returns the DocumentNumbers field value if set, zero value otherwise.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetDocumentNumbers() RightToWorkBreakdownDataValidationBreakdownDocumentNumbers {
	if o == nil || IsNil(o.DocumentNumbers) {
		var ret RightToWorkBreakdownDataValidationBreakdownDocumentNumbers
		return ret
	}
	return *o.DocumentNumbers
}

// GetDocumentNumbersOk returns a tuple with the DocumentNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetDocumentNumbersOk() (*RightToWorkBreakdownDataValidationBreakdownDocumentNumbers, bool) {
	if o == nil || IsNil(o.DocumentNumbers) {
		return nil, false
	}
	return o.DocumentNumbers, true
}

// HasDocumentNumbers returns a boolean if a field has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) HasDocumentNumbers() bool {
	if o != nil && !IsNil(o.DocumentNumbers) {
		return true
	}

	return false
}

// SetDocumentNumbers gets a reference to the given RightToWorkBreakdownDataValidationBreakdownDocumentNumbers and assigns it to the DocumentNumbers field.
func (o *RightToWorkBreakdownDataValidationBreakdown) SetDocumentNumbers(v RightToWorkBreakdownDataValidationBreakdownDocumentNumbers) {
	o.DocumentNumbers = &v
}

// GetDocumentExpiration returns the DocumentExpiration field value if set, zero value otherwise.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetDocumentExpiration() DocumentBreakdownDataComparisonBreakdownIssuingCountry {
	if o == nil || IsNil(o.DocumentExpiration) {
		var ret DocumentBreakdownDataComparisonBreakdownIssuingCountry
		return ret
	}
	return *o.DocumentExpiration
}

// GetDocumentExpirationOk returns a tuple with the DocumentExpiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetDocumentExpirationOk() (*DocumentBreakdownDataComparisonBreakdownIssuingCountry, bool) {
	if o == nil || IsNil(o.DocumentExpiration) {
		return nil, false
	}
	return o.DocumentExpiration, true
}

// HasDocumentExpiration returns a boolean if a field has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) HasDocumentExpiration() bool {
	if o != nil && !IsNil(o.DocumentExpiration) {
		return true
	}

	return false
}

// SetDocumentExpiration gets a reference to the given DocumentBreakdownDataComparisonBreakdownIssuingCountry and assigns it to the DocumentExpiration field.
func (o *RightToWorkBreakdownDataValidationBreakdown) SetDocumentExpiration(v DocumentBreakdownDataComparisonBreakdownIssuingCountry) {
	o.DocumentExpiration = &v
}

// GetExpiryDate returns the ExpiryDate field value if set, zero value otherwise.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetExpiryDate() DocumentBreakdownDataComparisonBreakdownIssuingCountry {
	if o == nil || IsNil(o.ExpiryDate) {
		var ret DocumentBreakdownDataComparisonBreakdownIssuingCountry
		return ret
	}
	return *o.ExpiryDate
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetExpiryDateOk() (*DocumentBreakdownDataComparisonBreakdownIssuingCountry, bool) {
	if o == nil || IsNil(o.ExpiryDate) {
		return nil, false
	}
	return o.ExpiryDate, true
}

// HasExpiryDate returns a boolean if a field has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) HasExpiryDate() bool {
	if o != nil && !IsNil(o.ExpiryDate) {
		return true
	}

	return false
}

// SetExpiryDate gets a reference to the given DocumentBreakdownDataComparisonBreakdownIssuingCountry and assigns it to the ExpiryDate field.
func (o *RightToWorkBreakdownDataValidationBreakdown) SetExpiryDate(v DocumentBreakdownDataComparisonBreakdownIssuingCountry) {
	o.ExpiryDate = &v
}

// GetMrz returns the Mrz field value if set, zero value otherwise.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetMrz() DocumentBreakdownDataComparisonBreakdownIssuingCountry {
	if o == nil || IsNil(o.Mrz) {
		var ret DocumentBreakdownDataComparisonBreakdownIssuingCountry
		return ret
	}
	return *o.Mrz
}

// GetMrzOk returns a tuple with the Mrz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) GetMrzOk() (*DocumentBreakdownDataComparisonBreakdownIssuingCountry, bool) {
	if o == nil || IsNil(o.Mrz) {
		return nil, false
	}
	return o.Mrz, true
}

// HasMrz returns a boolean if a field has been set.
func (o *RightToWorkBreakdownDataValidationBreakdown) HasMrz() bool {
	if o != nil && !IsNil(o.Mrz) {
		return true
	}

	return false
}

// SetMrz gets a reference to the given DocumentBreakdownDataComparisonBreakdownIssuingCountry and assigns it to the Mrz field.
func (o *RightToWorkBreakdownDataValidationBreakdown) SetMrz(v DocumentBreakdownDataComparisonBreakdownIssuingCountry) {
	o.Mrz = &v
}

func (o RightToWorkBreakdownDataValidationBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RightToWorkBreakdownDataValidationBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Gender) {
		toSerialize["gender"] = o.Gender
	}
	if !IsNil(o.DateOfBirth) {
		toSerialize["date_of_birth"] = o.DateOfBirth
	}
	if !IsNil(o.DocumentNumbers) {
		toSerialize["document_numbers"] = o.DocumentNumbers
	}
	if !IsNil(o.DocumentExpiration) {
		toSerialize["document_expiration"] = o.DocumentExpiration
	}
	if !IsNil(o.ExpiryDate) {
		toSerialize["expiry_date"] = o.ExpiryDate
	}
	if !IsNil(o.Mrz) {
		toSerialize["mrz"] = o.Mrz
	}
	return toSerialize, nil
}

type NullableRightToWorkBreakdownDataValidationBreakdown struct {
	value *RightToWorkBreakdownDataValidationBreakdown
	isSet bool
}

func (v NullableRightToWorkBreakdownDataValidationBreakdown) Get() *RightToWorkBreakdownDataValidationBreakdown {
	return v.value
}

func (v *NullableRightToWorkBreakdownDataValidationBreakdown) Set(val *RightToWorkBreakdownDataValidationBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableRightToWorkBreakdownDataValidationBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableRightToWorkBreakdownDataValidationBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRightToWorkBreakdownDataValidationBreakdown(val *RightToWorkBreakdownDataValidationBreakdown) *NullableRightToWorkBreakdownDataValidationBreakdown {
	return &NullableRightToWorkBreakdownDataValidationBreakdown{value: val, isSet: true}
}

func (v NullableRightToWorkBreakdownDataValidationBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRightToWorkBreakdownDataValidationBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
